encoding: utf-8
title: SwissUpLabs docs
email: support@swissuplabs.com
description: > # this means to ignore newlines until "baseurl:"
  SwissUpLabs extensions and themes documentation for Magento and Magento2
baseurl: ""
url: "http://swissup.github.io"

permalink: pretty

safe: true
lsi: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - bower_components/classie/
  - bower_components/desandro-matches-selector/
  - bower_components/doc-ready/
  - bower_components/ev-emitter/
  - bower_components/eventEmitter/
  - bower_components/eventie/
  - bower_components/fizzy-ui-utils/
  - bower_components/get-size/
  - bower_components/get-style-property/
  - bower_components/jquery/sizzle/
  - bower_components/jquery/src/
  - bower_components/outlayer/
  - bower_components/lunr.js/example/
  - bower_components/lunr.js/lib/
  - bower_components/lunr.js/test/
  - bower_components/matches-selector/
  - bower_components/material-design-lite/src/
  - bower_components/material-design-lite/utils/
  - bower_components/mustache/bin/
  - bower_components/mustache/hooks/
  - bower_components/mustache/spec/
  - bower_components/mustache/wrappers/
  - bower_components/tap-listener/
  - bower_components/unidragger/
  - bower_components/unipointer/

github:
  repository_url: https://github.com/swissup/swissup.github.io

prose:
  siteurl: "http://swissup.github.io/"
  media: "media"
  ignore:
    - .gitignore
    - bower.json
    - _config.yml
    - search.json
    - /_includes
    - /_layouts
    - /_posts
    - /bower_components
