- title: Extensions
  items:
    - title: AjaxLayeredNavigation
      url: /extensions/ajaxlayerednavigation/

    - title: AjaxPro
      url: /extensions/ajaxpro/

    - title: AjaxSearch
      url: /extensions/ajaxsearch/

    - title: Askit
      url: /extensions/askit/

    - title: Cache
      url: /extensions/cache/

    - title: Crawler
      url: /extensions/crawler/

    - title: EasyBanners
      url: /extensions/easybanners/

    - title: Email
      url: /extensions/email/

    - title: Helpmate
      url: /extensions/helpmate/

    - title: Highlight
      url: /extensions/highlight/

    - title: Navigation Pro
      url: /extensions/navigationpro/

    - title: Prolabels
      url: /extensions/prolabels/

    - title: Sold Together
      url: /extensions/soldtogether/

    - title: Review Reminder
      url: /extensions/reviewreminder/

# - title: Themes
#   items:
#     - title: Absolute Theme
#       url: /themes/f001-absolute/
#       free: 1

#     - title: Classic Theme
#       url: /themes/f002-classic/
#       free: 1

#     - title: Mobile Star Theme
#       url: /themes/m001-mobile-star/
