- title: Magento 1.x Extensions
  items:

    - title: AbandonedCart
      url: /m1/abandonedcart/

    - title: AjaxLayeredNavigation
      url: /m1/ajaxlayerednavigation/

    - title: AjaxPro
      url: /m1/ajaxpro/

    - title: AjaxSearch
      url: /m1/ajaxsearch/

    - title: Askit
      url: /m1/askit/

    - title: Attributepages
      url: /m1/attributepages/

    - title: Cache
      url: /m1/cache/

    - title: Countdowntimer
      url: /m1/countdowntimer/

    - title: Crawler
      url: /m1/crawler/

    - title: Daily Deals
      url: /m1/dailydeals/

    - title: EasyBanners
      url: /m1/easybanners/

    - title: Easy Catalog Images
      url: /m1/catalogimages/

    - title: Easy Color Swatches
      url: /m1/colorswatches/

    - title: Email
      url: /m1/email/

    - title: EasySlider
      url: /m1/easyslider/

    - title: EasyTabs
      url: /m1/easytabs/

    - title: Helpmate
      url: /m1/helpmate/

    - title: Highlight
      url: /m1/highlight/

    - title: Improved Admin Security
      url: /m1/improvedadminsecurity/

    - title: Lightbox Pro
      url: /m1/lightboxpro/

    - title: Navigation Pro
      url: /m1/navigationpro/

    - title: Newsletter Booster
      url: /m1/newsletterbooster/

    - title: Prolabels
      url: /m1/prolabels/

    - title: Product Videos
      url: /m1/productvideos/

    - title: Quick Shopping
      url: /m1/quickshopping/

    - title: Sold Together
      url: /m1/soldtogether/

    - title: Review Reminder
      url: /m1/reviewreminder/

    - title: Rich Snippets
      url: /m1/richsnippets/

    - title: Testimonials
      url: /m1/testimonials/

- title: Magento 2.x Extensions
  items:
    - title: Highlight
      url: /m2/highlight/

    - title: Review Reminder
      url: /m2/reviewreminder/

    - title: Store Maintenance
      url: /m2/store-maintenance/

    - title: Email
      url: /m2/email/

    - title: EasyTabs
      url: /m2/easytabs/

    - title: Testimonials
      url: /m2/testimonials/

    - title: Easy Catalog Images
      url: /m2/catalogimages/

# - title: Themes
#   items:
#     - title: Absolute Theme
#       url: /themes/f001-absolute/
#       free: 1

#     - title: Classic Theme
#       url: /themes/f002-classic/
#       free: 1

#     - title: Mobile Star Theme
#       url: /themes/m001-mobile-star/
