- title: Magento 1.x Extensions
  items:
    - title: AjaxLayeredNavigation
      url: /m1/ajaxlayerednavigation/

    - title: AjaxPro
      url: /m1/ajaxpro/

    - title: AjaxSearch
      url: /m1/ajaxsearch/

    - title: Askit
      url: /m1/askit/

    - title: Cache
      url: /m1/cache/

    - title: Crawler
      url: /m1/crawler/

    - title: EasyBanners
      url: /m1/easybanners/

    - title: Email
      url: /m1/email/

    - title: Helpmate
      url: /m1/helpmate/

    - title: Highlight
      url: /m1/highlight/

    - title: Navigation Pro
      url: /m1/navigationpro/

    - title: Prolabels
      url: /m1/prolabels/

    - title: Sold Together
      url: /m1/soldtogether/

    - title: Review Reminder
      url: /m1/reviewreminder/

- title: Magento 2.x Extensions
  items:
    - title: Highlight
      url: /m2/highlight/

    - title: Store Maintenance
      url: /m2/store-maintenance/

    - title: Email
      url: /m2/email/

# - title: Themes
#   items:
#     - title: Absolute Theme
#       url: /themes/f001-absolute/
#       free: 1

#     - title: Classic Theme
#       url: /themes/f002-classic/
#       free: 1

#     - title: Mobile Star Theme
#       url: /themes/m001-mobile-star/
