- title: Extensions
  items:
    - title: AjaxLayeredNavigation
      url: /extensions/ajaxlayerednavigation/

    - title: AjaxPro
      url: /extensions/ajaxpro/

    - title: AjaxSearch
      url: /extensions/ajaxsearch/

    - title: Askit
      url: /extensions/askit/

    - title: Attributepages
      url: /extensions/attributepages/

    - title: Cache
      url: /extensions/cache/

    - title: Configurable Swatches
      url: /extensions/catalog-configurable-swatches/
      free: 1

    - title: Crawler
      url: /extensions/crawler/

    - title: EasyBanners
      url: /extensions/easybanners/

    - title: EasyCatalogImages
      url: /extensions/easycatalogimages/
      free: 1

    - title: Email
      url: /extensions/email/

    - title: Firecheckout
      url: /extensions/firecheckout/

    - title: Helpmate
      url: /extensions/helpmate/

    - title: Highlight
      url: /extensions/highlight/

    - title: Navigation Pro
      url: /extensions/navigationpro/

    - title: Order Attachments
      url: /extensions/order-attachments/

    - title: Sold Together
      url: /extensions/soldtogether/

    - title: Testimonials
      url: /extensions/testimonials/
      free: 1

    - title: Review Reminder
      url: /extensions/reviewreminder/

    - title: Rich Snippets
      url: /extensions/richsnippets/

# - title: Themes
#   items:
#     - title: Absolute Theme
#       url: /themes/f001-absolute/
#       free: 1

#     - title: Classic Theme
#       url: /themes/f002-classic/
#       free: 1

#     - title: Mobile Star Theme
#       url: /themes/m001-mobile-star/
